import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Word Desk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome To Work Desk Web Application</h1>
      </main>
    </>
  );
}
